model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.VQModel
  project: LDM-VQ-base
  params:
    embed_dim: 3
    n_embed: 8192
    monitor: val/rec_loss

    ddconfig:
      double_z: false
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 250001
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  data_root: /globalscratch/mridul/data/mini-imagenet_split_test
  params:
    batch_size: 20
    num_workers: 8
    wrap: true
    train:
      target: ldm.data.imagenet.ImageNetTrain
      # data_root: /globalscratch/mridul/data/mini-imagenet_split_test
      params:
        config:
          size: 256
    validation:
      target: ldm.data.imagenet.ImageNetValidation
      # data_root: /globalscratch/mridul/data/mini-imagenet_split_test
      params:
        config:
          size: 256


