model:
  base_learning_rate: 1.0e-06
  target: ldm.models.vqgan_dual_non_dict.VQModelDual
  project: I2SB-VQ-BASE
  params:
    embed_dim: 3
    n_embed: 8192
    monitor: val/rec_loss

    ddconfig:
      double_z: false
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.75
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 10
    num_workers: 8
    wrap: true
    train:
      target: ldm.data.i2sb_dataloader.pix2pixDataset
      params:
        dataset: edges2shoes
        split: train
    validation:
      target: ldm.data.i2sb_dataloader.pix2pixDataset
      params:
        dataset: edges2shoes
        split: val

