DEVICE: 0

num_workers: 8
batch_size: 12 #100


lr: 0.0001
step_size: 140
num_epochs: 140

model_path: "/projects/ml4science/mridul/ldm/cub_samples/classification/models/resnet50_epoch140_lr0.0001_batch12.path"


# Just set pretrained_model to None for training species level
# pretrained_model: None


size: 256

file_list_path_train: "/fastscratch/mridul/cub_190_split_resized/official/CUB_200_2011/train_segmented_imagenet_background_bb_crop_256.txt"
file_list_path_test: "/fastscratch/mridul/cub_190_split_resized/official/CUB_200_2011/test_segmented_imagenet_background_bb_crop_256.txt"
# size= 512
# file_list_path = "/home/elhamod/data/Fish/taming_transforms_fish_train_padded_512.txt"
# file_list_path: "/home/elhamod/data/Fish/taming_transforms_fish_test_small.txt" # Just for test

##############