DEVICE: 0

num_workers: 8
batch_size: 100 #100


lr: 0.001
step_size: 17
num_epochs: 60

# model_path: "/globalscratch/mridul/ldm/classification/models/resnet34_model_epoch_30_lr0.001_step4.path"

# model_path: "/globalscratch/mridul/ldm/final_runs_eccv/fish_classification/resnet18_epoch50_level1.path"
model_path: /globalscratch/mridul/ldm/classification/models/classification_model_epoch_60_new_again.path


# Just set pretrained_model to None for training species level
# pretrained_model: None


size: 256
# file_list_path_train: "/fastscratch/mridul/fishes/fishes_train_diffusion_new.txt"
# file_list_path_test: "/fastscratch/mridul/fishes/fishes_test_diffusion_new.txt"

file_list_path_train: "/fastscratch/elhamod/data/Fish/fish_train.txt"
file_list_path_test: "/fastscratch/elhamod/data/Fish/fish_test.txt"

# file_list_path_train: "/globalscratch/mridul/data/fishes_levels/level1_train.txt"
# file_list_path_test: "/globalscratch/mridul/data/fishes_levels/level1_test.txt"


# size= 512
# file_list_path = "/home/elhamod/data/Fish/taming_transforms_fish_train_padded_512.txt"
# file_list_path: "/home/elhamod/data/Fish/taming_transforms_fish_test_small.txt" # Just for test

##############