DEVICE: 0

num_workers: 8
batch_size: 100 #100


lr: 0.001
step_size: 7
num_epochs: 10

# model_path: "/globalscratch/mridul/ldm/classification/models/resnet34_model_epoch_30_lr0.001_step4.path"

# model_path: "/globalscratch/mridul/ldm/final_runs_eccv/fish_classification/resnet18_epoch10_leave_out_3species.path"
model_path: "/globalscratch/mridul/ldm/final_runs_eccv/fish_classification/resnet18_epoch10_unseen.path"



size: 256
file_list_path_train: "/globalscratch/mridul/ldm/final_runs_eccv/fishes_samples/multi_level/3species/new_set/train.txt"
file_list_path_test: "/globalscratch/mridul/ldm/final_runs_eccv/fishes_samples/multi_level/3species/new_set/test.txt"

# file_list_path_train: "/globalscratch/mridul/ldm/final_runs_eccv/fishes_samples/multi_level/3species/leave_out_species_train.txt"
# file_list_path_test: "/globalscratch/mridul/ldm/final_runs_eccv/fishes_samples/multi_level/3species/leave_out_species_test.txt"


##############