DEVICE: 0

num_workers: 8
batch_size: 200

file_prefix: "tsne-test-set"

img_res: 256
dataset_path:  /fastscratch/elhamod/data/Fish/fish_test.txt

ckpt_path: /fastscratch/elhamod/logs/PhyloNN/checkpoints/last.ckpt
yaml_path: /fastscratch/elhamod/logs/PhyloNN/configs/2023-01-15T00-45-57-project.yaml

# Just set phylogeny_path to None for training species level
level: 1
phyloDistances_string: "0.77,0.5,0.33"
phylogeny_path: /fastscratch/elhamod/data/Fish

phylogeny_knn: /fastscratch/elhamod/data/Fish

which_tsne_plots: ['standard', 'knn']