DEVICE: 0

num_workers: 8
batch_size: 200

model_name: VQ

file_prefix: "VQ"
img_res: 256
dataset_path: "/fastscratch/elhamod/data/Fish/fish_train.txt"

## cw
# ckpt_path: /fastscratch/mridul/new_diffusion_models/ldm/cw-base/2023-10-27T15-30-52_vqcw_f8_batch16_channels64_lr4.5e6/checkpoints/epoch=000017.ckpt
# yaml_path: /fastscratch/mridul/new_diffusion_models/ldm/cw-base/2023-10-27T15-30-52_vqcw_f8_batch16_channels64_lr4.5e6/configs/2023-10-27T15-30-52-project-inference.yaml

## above vq
ckpt_path: /fastscratch/mridul/new_diffusion_models/ldm/vq-base/2023-10-24T17-42-38_vq_f8-batch16-channels_64/checkpoints/epoch=000245.ckpt
yaml_path: /fastscratch/mridul/new_diffusion_models/ldm/vq-base/2023-10-24T17-42-38_vq_f8-batch16-channels_64/configs/2023-10-24T17-42-38-project.yaml


# Just set phylogeny_path to None when not applicable
# phylogeny_path: None

phylogeny_knn: /fastscratch/elhamod/data/Fish

which_tsne_plots: ['standard', 'knn']
legend_labels: ['class']