model:
  base_learning_rate:  5.0e-07
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  project: test
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: class_label
    image_size: 64
    channels: 3
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss
    use_ema: False
    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler_step
      params:
        warm_up_steps: [751]
        cycle_lengths: [10000000000000]
        f_start: [1.0e-06]
        f_max: [1.]
        f_min: [ 1.]
        verbosity_interval: 50.0
        step_size: 250
        gamma: 0.9

    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 192
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 5
        num_heads: 1
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
    
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        # ckpt_path: configs/vq-gan/vanilla-vqgan.yaml
        # ckpt_path: /home/mridul/latent-diffusion/logs/run1/2023-09-01T14-41-51_run1run1/checkpoints/last.ckpt
        ckpt_path: /globalscratch/mridul/ldm/imagenet/vq-base/2023-10-09T04-31-39_vq_f4_mini-imagenet_batch20/checkpoints/last.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    
    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder
      params:
        n_classes: 100
        embed_dim: 512
        key: class_label


data:
  target: main.DataModuleFromConfig
  data_root: /globalscratch/mridul/data/mini-imagenet_split_test
  params:
    batch_size: 40
    num_workers: 8
    wrap: true
    train:
      target: ldm.data.imagenet.ImageNetTrain
      # data_root: /globalscratch/mridul/data/mini-imagenet_split_test
      params:
        config:
          size: 256
    validation:
      target: ldm.data.imagenet.ImageNetValidation
      # data_root: /globalscratch/mridul/data/mini-imagenet_split_test
      params:
        config:
          size: 256


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 50000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True