model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  project: LDM
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: class_label
    image_size: 16
    channels: 16
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    # num_classes: 38
    # scale_by_std: false
    # scale_factor: 0.22765929

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 16
        in_channels: 16
        out_channels: 16
        model_channels: 256
        attention_resolutions:
        # - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        # - 3
        - 4
        # use_scale_shift_norm: false
        # resblock_updown: false
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
        # use_checkpoint: true
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        monitor: val/rec_loss
        embed_dim: 16
        ckpt_path: /fastscratch/mridul/new_diffusion_models/ldm/kl-base/2023-09-21T11-56-57_KL_16/checkpoints/epoch=000485.ckpt
        ddconfig:
          double_z: true
          z_channels: 16
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder
      params:
        n_classes: 38
        embed_dim: 512
        key: class

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8
    wrap: true
    train:
      target: ldm.data.custom.CustomTrain
      params:
        training_images_list_file: /fastscratch/elhamod/data/Fish/fish_train.txt
        size: 256
        add_labels: true
    validation:
      target: ldm.data.custom.CustomTest
      params:
        test_images_list_file: /fastscratch/elhamod/data/Fish/fish_test.txt
        size: 256
        add_labels: true

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 100000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True